### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
x-token : abcBolinhasToken
x-key : abcBolinhasKey
### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1
x-token : abcBolinhasTokenn
x-key : abcBolinhasKey
### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json
x-token : abcBolinhasToken
x-key : abcBolinhasKey

{
    "nome": "dudinha",
    "cpf": "07698139076",
    "telefone": "49898989",
    "comprar_fiado": true,
    "dia_fiado": 13,
    "senha": "abc"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json
x-token : abcBolinhasToken
x-key : abcBolinhasKey

{
    
    "nome": "aa",
    "cpf": "07698139076",
    "telefone": "49898989",
    "comprar_fiado": true,
    "dia_fiado": 13,
    "senha": "abc"
  
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
x-token : abcBolinhasToken
x-key : abcBolinhasKey
