### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token : abcBolinhasToken
x-key : abcBolinhasKey
### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1 #Consulta
x-token : abcBolinhasTokenn1
x-key : abcBolinhasKey

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1 #Inserir
x-token : abcBolinhasToken
x-key : abcBolinhasKey
content-type: application/json

{
    "nome": "Abcd da ilva",
    "cpf": "019238656",
    "telefone": "4998834567",
    "senha": "bolis",
    "matricula": "145",
    "grupo": 1
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1 #edita
content-type: application/json
x-token : abcBolinhasToken
x-key : abcBolinhasKey

{
    "nome": "Bolinhas dos Testes",
    "cpf": "12345678909",
    "telefone": "49898989",
    "senha": "abc",
    "matricula": "54321",
    "grupo": 2
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
x-token : abcBolinhasToken
x-key : abcBolinhasKey
